# Generated by Django 5.1.4 on 2024-12-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelo', '0002_rename_titulo_comentario_nome_alter_comentario_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(default='pedro@palma.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idade',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='comentario',
            name='telefone',
            field=models.CharField(default='14996014525', max_length=15),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(default='Pedro Gabriel', max_length=100),
        ),
    ]
